name: Gradle Tests

on:
  push:
    branches:
      - main  # Adjust this based on your branch
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'  # Change this to your required version
          cache: 'gradle'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradle/gradlew

      - name: Run tests
        run: |
          cd gradle
          ./gradlew test
